services:
  app:
    image: ghcr.io/panelzap/panelzap:0.1.0
    volumes:
      - .:/var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - APP_NAME="Nome do seu painel"
      - APP_ENV=production
      - APP_KEY="base64:dq5WQ9pRnnOy5lpOl/cXqpljkXr4AOI5OiG/lvVnoI0="
      - APP_DEBUG="false"
      - APP_TIMEZONE=America/Sao_Paulo
      - APP_URL=https://suaurldopainel.com.br
      - APP_LOGO_PATH=/images/app-logo.svg
      - APP_LOCALE=pt_BR
      - APP_MAINTENANCE_DRIVER=file
      - PHP_CLI_SERVER_WORKERS=4
      - BCRYPT_ROUNDS=12
      - LOG_CHANNEL=stack
      - LOG_STACK=single
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql  # tipo de conexao
      - DB_HOST=mysql    
      - DB_PORT="3306"
      - DB_DATABASE=database 
      - DB_USERNAME=usuario
      - DB_PASSWORD=suasenhadomysql
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=120
      - SESSION_ENCRYPT="false"
      - SESSION_PATH=/
      - SESSION_DOMAIN=null
      - BROADCAST_CONNECTION=log
      - FILESYSTEM_DISK=local
      - QUEUE_CONNECTION=database
      - CACHE_STORE=database
      - CACHE_PREFIX=""
      - MEMCACHED_HOST=127.0.0.1
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT="6379"
      - MAIL_MAILER=log
      - MAIL_SCHEME=null
      - MAIL_HOST=127.0.0.1
      - MAIL_PORT="2525"
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_FROM_ADDRESS=hello@example.com
      - MAIL_FROM_NAME="${APP_NAME}"
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET=""
      - AWS_USE_PATH_STYLE_ENDPOINT="false"
      - VITE_APP_NAME="${APP_NAME}"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.panelzap.rule=Host(`suaurldopainel.com.br`)
        - traefik.http.routers.panelzap.entrypoints=websecure
        - traefik.http.routers.panelzap.tls.certresolver=letsencryptresolver
        - traefik.http.routers.panelzap.middlewares=redirect-to-https
        - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
        - traefik.http.services.panelzap.loadbalancer.server.scheme=http
        - traefik.http.services.panelzap.loadbalancer.server.port=8000
    ports:
      - "8000:8000"
    networks:
      - painel_default  # sua rede