name: Docker Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Converter o nome do repositório para lowercase
      - name: Convert repository name to lowercase
        run: echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Construir a imagem Docker
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ env.REPO_NAME }}:latest .
          docker build -t ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }} .

      # Fazer push das imagens
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ env.REPO_NAME }}:latest
          docker push ghcr.io/${{ env.REPO_NAME }}:${{ github.ref_name }}
