name: Docker Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Converter o nome do repositório para lowercase
      - name: Convert to lowercase
        id: convert
        run: |
          lower_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "lower_name=${lower_name}" >> $GITHUB_ENV

      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fazer login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Construir e enviar a imagem mais recente para ambas as plataformas (amd64 e arm64)
      - name: Build the Docker Image Latest
        run: |
          docker build -t ghcr.io/${{ env.lower_name }}:latest . --push

      # Construir e enviar as imagens (latest e version) para ambas as plataformas (amd64 e arm64)
      - name: Build and Push Docker Images
        run: |
          docker build -t ghcr.io/${{ env.lower_name }}:${{ github.ref_name }} . --push
