name: Docker Build

on:
  push:
    branches:
      - main
      
# on:
#   release:
#     types:
#       - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout mode
        uses: actions/checkout@v3
      - name: Login to github container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build the Docker Image Latest
        run: docker build -t ghcr.io/${{ github.repository }}:latest .
      - name: Push the Docker Image Latest
        run: docker push ghcr.io/${{ github.repository }}:latest
      - name: Build the Docker Image Version
        run: docker build -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} .
      - name: Push the Docker Image Version
        run: docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
