name: Docker Build

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Converter o nome do repositório para lowercase
      - name: Convert to lowercase
        id: convert
        run: |
          lower_name=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "lower_name=${lower_name}" >> $GITHUB_ENV

      # Fazer checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fazer login no GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      # Configurar o QEMU para suportar múltiplas arquiteturas
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Configurar o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Construir e enviar as imagens (latest e version) para ambas as plataformas (amd64 e arm64)
      - name: Build and Push Docker Images
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ghcr.io/${{ env.lower_name }}:latest \
            -t ghcr.io/${{ env.lower_name }}:${{ github.ref_name }} \
            . --push
